sonar.projectKey=warchi-frontend
sonar.projectName=warchi-frontend
sonar.sources=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourcesEncoding=UTF-8
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.vue

# Quality Gate thresholds
sonar.qualitygate.wait=true
sonar.qualitygate.conditions.coverage=70
sonar.qualitygate.conditions.new_coverage=70
sonar.qualitygate.conditions.duplications=10
