sonar.projectKey=warchi-frontend
sonar.projectName=warchi-frontend
sonar.sources=src
sonar.tests=test
sonar.test.inclusion=**/*.spec.ts,**/*.test.ts
sonar.ts.lcov.reportPaths=coverage/lcov.info
sonar.sourcesEncoding=UTF-8
