apiVersion: v1
kind: Service
metadata:
  name: {{ include "warchi.fullname" . }}
  labels:
    {{- include "warchi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.tlsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "warchi.selectorLabels" . | nindent 4 }}
    {{- if .Values.blueGreen.enabled }}
    app.kubernetes.io/color: {{ .Values.blueGreen.activeColor | default "blue" | quote }}
    {{- end }}
