FROM eclipse-temurin:25-jre-alpine
RUN mkdir -p /root/.postgresql
ADD https://storage.yandexcloud.net/cloud-certs/CA.pem /root/.postgresql/root.crt
WORKDIR /app
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
