FROM eclipse-temurin:25-jre-alpine
RUN apk upgrade --no-cache \
    && apk add --no-cache curl \
    && mkdir -p /root/.postgresql \
    && curl -sf https://storage.yandexcloud.net/cloud-certs/CA.pem \
       -o /root/.postgresql/root.crt \
    && apk del curl
WORKDIR /app
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
