/**
 * SVG icons from public/icons/ - same set as in notation editor NodeStylePanel
 */
export const AVAILABLE_ICONS = [
  'actor',
  'artifact',
  'assessment',
  'capability',
  'circle',
  'collaboration',
  'communication_network',
  'component_group',
  'component',
  'constraint',
  'contract',
  'course_of_action',
  'deliverable',
  'device',
  'distribution_network',
  'driver',
  'equipment',
  'event',
  'facility',
  'function',
  'gap',
  'goal',
  'group',
  'grouping',
  'hidden_rectangle',
  'interaction',
  'interface',
  'location',
  'material',
  'meaning',
  'node',
  'object',
  'octagon',
  'outcome',
  'path',
  'plateau',
  'principle',
  'process',
  'product',
  'rectangle',
  'representation',
  'requirement',
  'resource',
  'rhombus',
  'role',
  'rounded_rectangle',
  'service',
  'stakeholder',
  'system_software',
  'text',
  'value_stream',
  'value',
  'work_package',
] as const

export type AvailableIcon = (typeof AVAILABLE_ICONS)[number]

export const AVAILABLE_ICON_OPTIONS = AVAILABLE_ICONS.map((name) => ({ id: name, label: name }))
