/**
 * Archimate-style SVG icons from public/icons/ (node icon on diagram, NodeStylePanel).
 */
export const ARCHIMATE_ICONS = [
  'actor',
  'artifact',
  'assessment',
  'capability',
  'circle',
  'collaboration',
  'communication_network',
  'component_group',
  'component',
  'constraint',
  'contract',
  'course_of_action',
  'deliverable',
  'device',
  'distribution_network',
  'driver',
  'equipment',
  'event',
  'facility',
  'function',
  'gap',
  'goal',
  'group',
  'grouping',
  'hidden_rectangle',
  'interaction',
  'interface',
  'location',
  'material',
  'meaning',
  'node',
  'object',
  'octagon',
  'outcome',
  'path',
  'plateau',
  'principle',
  'process',
  'product',
  'rectangle',
  'representation',
  'requirement',
  'resource',
  'rhombus',
  'role',
  'rounded_rectangle',
  'service',
  'stakeholder',
  'system_software',
  'text',
  'value_stream',
  'value',
  'work_package',
] as const

export type ArchimateIcon = (typeof ARCHIMATE_ICONS)[number]

export type IconOption = { id: string; label: string }

export const ARCHIMATE_ICON_OPTIONS: IconOption[] = ARCHIMATE_ICONS.map((name) => ({
  id: name,
  label: name,
}))
