apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: warchi-site-ru-tls
  namespace: arch
spec:
  secretName: warchi-site-ru-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - warchi.ru
